DROP DATABASE IF EXISTS election_db;
CREATE DATABASE election_db;
USE election_db;
CREATE TABLE voters_result 
(
    voter	VARCHAR(512),
    candidate	VARCHAR(512)
);

INSERT INTO voters_result (voter, candidate) VALUES ('Kathy', '');
INSERT INTO voters_result (voter, candidate) VALUES ('Charles', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Charles', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Charles', 'Kathy');
INSERT INTO voters_result (voter, candidate) VALUES ('Benjamin', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Anthony', 'Paul');
INSERT INTO voters_result (voter, candidate) VALUES ('Anthony', 'Anthony');
INSERT INTO voters_result (voter, candidate) VALUES ('Edward', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Edward', 'Paul');
INSERT INTO voters_result (voter, candidate) VALUES ('Edward', 'Kathy');
INSERT INTO voters_result (voter, candidate) VALUES ('Terry', '');
INSERT INTO voters_result (voter, candidate) VALUES ('Nancy', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Nancy', 'Nicole');
INSERT INTO voters_result (voter, candidate) VALUES ('Nancy', 'Paul');
INSERT INTO voters_result (voter, candidate) VALUES ('Nancy', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Nancy', 'Kathy');
INSERT INTO voters_result (voter, candidate) VALUES ('Evelyn', 'Anthony');
INSERT INTO voters_result (voter, candidate) VALUES ('Evelyn', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Evelyn', 'Paul');
INSERT INTO voters_result (voter, candidate) VALUES ('Evelyn', 'Nicole');
INSERT INTO voters_result (voter, candidate) VALUES ('Shirley', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Shirley', 'Nicole');
INSERT INTO voters_result (voter, candidate) VALUES ('Shirley', 'Kathy');
INSERT INTO voters_result (voter, candidate) VALUES ('Shirley', 'Anthony');
INSERT INTO voters_result (voter, candidate) VALUES ('Victor', '');
INSERT INTO voters_result (voter, candidate) VALUES ('Bobby', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Bobby', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Helen', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Helen', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Helen', 'Kathy');
INSERT INTO voters_result (voter, candidate) VALUES ('Helen', 'Nicole');
INSERT INTO voters_result (voter, candidate) VALUES ('Kevin', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Kevin', 'Kathy');
INSERT INTO voters_result (voter, candidate) VALUES ('Kevin', 'Paul');
INSERT INTO voters_result (voter, candidate) VALUES ('Betty', '');
INSERT INTO voters_result (voter, candidate) VALUES ('Andrew', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Andrew', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Martha', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Martha', 'Anthony');
INSERT INTO voters_result (voter, candidate) VALUES ('Marie', 'Anthony');
INSERT INTO voters_result (voter, candidate) VALUES ('Alan', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Matthew', 'Nicole');
INSERT INTO voters_result (voter, candidate) VALUES ('Matthew', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Arthur', '');
INSERT INTO voters_result (voter, candidate) VALUES ('Joyce', '');
INSERT INTO voters_result (voter, candidate) VALUES ('Ryan', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Nicole', 'Nicole');
INSERT INTO voters_result (voter, candidate) VALUES ('Paul', '');
INSERT INTO voters_result (voter, candidate) VALUES ('Christine', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Christine', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Kathy', 'Kathy');
INSERT INTO voters_result (voter, candidate) VALUES ('Kathy', 'Christine');
INSERT INTO voters_result (voter, candidate) VALUES ('Kathy', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Kathy', 'Nicole');
INSERT INTO voters_result (voter, candidate) VALUES ('Anthony', 'Anthony');
INSERT INTO voters_result (voter, candidate) VALUES ('Anthony', 'Ryan');
INSERT INTO voters_result (voter, candidate) VALUES ('Anthony', 'Paul');
